### ISSUE TITLE
Documentation needs to be clearly written.

### ISSUE THREAD

**Issue by waseefakhtar** [intuit/AnimatedFormFieldTableViewCell#1]
This is a great project! However, the README file needs to be clearly written on how to install, setup, and use AnimatedFormFieldTableViewCell with code examples.

**Comment by zaltzy** [comment]
Hi @waseefakhtar 
Thanks for your input. I've taken this to my attention and updated the repository with clearer instructions and a demo project. I've also removed a lot of useless files from the repo so things are a bit more organized, and also I'll be adding a Swift 3 version soon.

Closing this for now - If the instructions are still unclear let me know and I'll reopen.
Sorry for the long time it took me to reply.
