### ISSUE TITLE
Setting up AnimatedFormFieldTableViewCell

### ISSUE THREAD

**Issue by waseefakhtar** [intuit/AnimatedFormFieldTableViewCell#2]
I want to use `AnimatedFormFieldTableViewCell` in my project but I can’t get my head around the steps for setting it up. So far, I’ve dragged the files from the folder and followed the steps as:

In order to use `AnimatedFormFieldTableViewCell`, all you have to do is:

1) Register the `AnimatedFormFieldTableViewCell` nib on the ViewController on which you are implementing your UITableView for your reuse identifier.

> override func viewDidLoad() {
>     super.viewDidLoad()
>     self.tableView.registerCellNib(AnimatedFormFieldTableViewCell)
> 
>     tableView.reloadData()
> }

2) Dequeue your cell on `CellForRowAtIndexPath` as a `AnimatedFormFieldTableViewCell`.

> func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
> 
>     let cellIdentifier = “cell”
>     let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! AnimatedFormFieldTableViewCell
> 
>     return cell
> }

3) Change the placeholder's label text by calling `setLabelText` on the cell itself.

> func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
> 
>     let cellIdentifier = “cell”
>     let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! AnimatedFormFieldTableViewCell
> 
>     cell.setLabelText("Enter title”)
> 
>     return cell
> }

Notes:

1) You can still implement `UITextFieldDelegate` the same way you would implement on a regular `UITextField`, you just need to define the AnimatedFormFieldTableViewCell's delegate (there is no need to directly define the delegate for the embedded `UITextField`).

2) In order to access the embedded UITextField you can simply call the cell's `cellTextField` property.

> I don’t get these last two steps.

If I run my app, I get the unexpectedly found nil on  `self.cellTextfield.delegate = self` in the `AnimatedFormFieldTableViewCell` class.

What am I missing?

**Comment by zaltzy** [comment]
Hi @waseefakhtar 
1) I see that you're using a method called "registerCellNib" - just to make sure: this method uses the same identifier you're using later on (in this case - "cell")?

2) Regarding the notes -
2.1) I've updated the readme file with a clearer explanation regarding the UITextFieldDelegate protocol usage in this project. Could you take a look there again and see if this clears things up for you?
2.2) If you need to access the textField directly when dequeuing the cell (Change style, font or whatever), you can do that by calling "cell.cellTextField".

3) Regarding the error you're receiving:
Does your view controller conform to the UITextFieldDelegate?

I've also added a demo project using the cell - this could also help you.

Let me know if this solved the issue for you.
