### ISSUE TITLE
Migrate to Swift 5.0

### ISSUE THREAD

**Issue by jogendra** [intuit/AnimatedFormFieldTableViewCell#4]
@zaltzy Can I work on migrating current code to swift 5?

**Comment by zaltzy** [comment]
Go ahead... But I no longer have admin privileges for this repo since I no longer work for Intuit (that's why I'm not maintaining this anymore). You can try creating a PR or just fork this repo and work from there..

**Comment by jogendra** [comment]
@zaltzy Done!

**Comment by zaltzy** [comment]
Got my push permissions back :) Merged your PR.
Thank you!
